[package]
name = "tfc-toolset"
version = "0.1.0"
description = "A toolset to help manage a toolset that helps manage your deployments"
authors = ["Christian Haynes <06chaynes@gmail.com>"]
repository = "https://github.com/06chaynes/tfc-toolset.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.61.0"

[dependencies]
anyhow = "1.0.66"
async-scoped = { version = "0.7.1", features = ["use-async-std"] }
config = "0.13.3"
log = "0.4.17"
miette = "5.5.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
surf = "2.3.2"
thiserror = "1.0.37"
url = "2.3.1"
