[package]
name = "tfc-toolset-extras"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-scoped = { version = "0.7.1", features = ["use-async-std"] }
config = "0.13.3"
log = "0.4.17"
miette = "5.5.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
surf = "2.3.2"
thiserror = "1.0.37"
url = "2.3.1"
surf-governor = "0.1.2"
http-cache-surf = "0.5.2"
surf-retry = "0.2.1"

[dependencies.tfc-toolset]
path = "../tfc-toolset"
version = "0.1.0"
