[package]
name = "tfc-toolset-extras"
version = "0.1.0"
edition = "2021"
rust-version = "1.67.1"

[dependencies]
anyhow = "1.0.75"
async-scoped = { version = "0.7.1", features = ["use-async-std"] }
config = "0.13.3"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
surf = "2.3.2"
thiserror = "1.0.49"
url = "2.4.1"
surf-governor = "0.2.0"
http-cache-surf = "0.11.4"
surf-retry = "0.3.1"

[dependencies.tfc-toolset]
path = "../tfc-toolset"
version = "0.1.0"
