[package]
name = "tfc-toolset-extras"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-scoped = { version = "0.7.0", features = ["use-async-std"] }
config = "0.13.1"
log = "0.4.17"
miette = "4.7.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
surf = "2.3.2"
thiserror = "1.0.31"
url = "2.2.2"
surf-governor = "0.1.0"
http-cache-surf = "0.4.6"
surf-retry = "0.1.0"

[dependencies.tfc-toolset]
path = "../tfc-toolset"
version = "0.1.0"
